# CMake generated Testfile for 
# Source directory: /home/runner/work/struetype/struetype/examples
# Build directory: /home/runner/work/struetype/struetype/build_compressed/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ProFontGrid "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/profont/ProFont.ttf")
set_tests_properties(ProFontGrid PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;21;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuMathTeXGyre "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuMathTeXGyre.ttf")
set_tests_properties(DejaVuMathTeXGyre PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSans-Bold "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSans-Bold.ttf")
set_tests_properties(DejaVuSans-Bold PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSans-BoldOblique "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSans-BoldOblique.ttf")
set_tests_properties(DejaVuSans-BoldOblique PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSans-ExtraLight "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSans-ExtraLight.ttf")
set_tests_properties(DejaVuSans-ExtraLight PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSans-Oblique "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSans-Oblique.ttf")
set_tests_properties(DejaVuSans-Oblique PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSans "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSans.ttf")
set_tests_properties(DejaVuSans PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSansCondensed-Bold "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSansCondensed-Bold.ttf")
set_tests_properties(DejaVuSansCondensed-Bold PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSansCondensed-BoldOblique "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSansCondensed-BoldOblique.ttf")
set_tests_properties(DejaVuSansCondensed-BoldOblique PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSansCondensed-Oblique "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSansCondensed-Oblique.ttf")
set_tests_properties(DejaVuSansCondensed-Oblique PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSansCondensed "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSansCondensed.ttf")
set_tests_properties(DejaVuSansCondensed PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSansMono-Bold "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSansMono-Bold.ttf")
set_tests_properties(DejaVuSansMono-Bold PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSansMono-BoldOblique "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSansMono-BoldOblique.ttf")
set_tests_properties(DejaVuSansMono-BoldOblique PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSansMono-Oblique "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSansMono-Oblique.ttf")
set_tests_properties(DejaVuSansMono-Oblique PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSansMono "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSansMono.ttf")
set_tests_properties(DejaVuSansMono PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSerif-Bold "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSerif-Bold.ttf")
set_tests_properties(DejaVuSerif-Bold PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSerif-BoldItalic "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSerif-BoldItalic.ttf")
set_tests_properties(DejaVuSerif-BoldItalic PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSerif-Italic "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSerif-Italic.ttf")
set_tests_properties(DejaVuSerif-Italic PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSerif "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSerif.ttf")
set_tests_properties(DejaVuSerif PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSerifCondensed-Bold "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSerifCondensed-Bold.ttf")
set_tests_properties(DejaVuSerifCondensed-Bold PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSerifCondensed-BoldItalic "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSerifCondensed-BoldItalic.ttf")
set_tests_properties(DejaVuSerifCondensed-BoldItalic PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSerifCondensed-Italic "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSerifCondensed-Italic.ttf")
set_tests_properties(DejaVuSerifCondensed-Italic PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(DejaVuSerifCondensed "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/dejavu/ttf/DejaVuSerifCondensed.ttf")
set_tests_properties(DejaVuSerifCondensed PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;27;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(STIXTwoMath-Regular "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/stix/ttf/STIXTwoMath-Regular.ttf")
set_tests_properties(STIXTwoMath-Regular PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;37;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(STIXTwoText-Bold "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/stix/ttf/STIXTwoText-Bold.ttf")
set_tests_properties(STIXTwoText-Bold PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;37;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(STIXTwoText-BoldItalic "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/stix/ttf/STIXTwoText-BoldItalic.ttf")
set_tests_properties(STIXTwoText-BoldItalic PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;37;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(STIXTwoText-Italic "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/stix/ttf/STIXTwoText-Italic.ttf")
set_tests_properties(STIXTwoText-Italic PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;37;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(STIXTwoText-Medium "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/stix/ttf/STIXTwoText-Medium.ttf")
set_tests_properties(STIXTwoText-Medium PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;37;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(STIXTwoText-MediumItalic "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/stix/ttf/STIXTwoText-MediumItalic.ttf")
set_tests_properties(STIXTwoText-MediumItalic PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;37;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(STIXTwoText-Regular "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/stix/ttf/STIXTwoText-Regular.ttf")
set_tests_properties(STIXTwoText-Regular PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;37;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(STIXTwoText-SemiBold "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/stix/ttf/STIXTwoText-SemiBold.ttf")
set_tests_properties(STIXTwoText-SemiBold PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;37;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(STIXTwoText-SemiBoldItalic "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/stix/ttf/STIXTwoText-SemiBoldItalic.ttf")
set_tests_properties(STIXTwoText-SemiBoldItalic PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;37;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(unifont-15 "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/unifont/unifont-15.0.06.ttf")
set_tests_properties(unifont-15 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;47;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(unifont_csur-15 "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/unifont/unifont_csur-15.0.06.ttf")
set_tests_properties(unifont_csur-15 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;47;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(unifont_jp-15 "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/unifont/unifont_jp-15.0.06.ttf")
set_tests_properties(unifont_jp-15 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;47;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
add_test(unifont_upper-15 "/home/runner/work/struetype/struetype/build_compressed/examples/genpng" "/home/runner/work/struetype/struetype/examples/unifont/unifont_upper-15.0.06.ttf")
set_tests_properties(unifont_upper-15 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/struetype/struetype/examples/CMakeLists.txt;47;add_test;/home/runner/work/struetype/struetype/examples/CMakeLists.txt;0;")
